"""Generate deterministic work order files for workers.

Purpose: Generate deterministic work order files for workers.
Rationale: Workers receive ad-hoc prose prompts from leads, causing reinterpretation,
  skipped steps, and improvisation. This module generates a structured, deterministic
  work order file (.work/orders/worker-<name>-task-<id>.md) that contains the exact
  contract: files to modify, fix description, test command, commit message format.
  The worker prompt becomes ONLY a pointer to this file.
Responsibility: Generate work order files from task spec + requirement data.
  NOT responsible for task lifecycle, assignment, or DAG transitions.
Organization: Standalone function generate_work_order(). See source."""

from __future__ import annotations

import os

from minion.db import get_db, get_runtime_dir


def generate_work_order(
    agent_name: str,
    task_id: int,
    worker_name: str,
    files_to_modify: str = "",
    fix_description: str = "",
    test_command: str = "",
    commit_message: str = "",
) -> dict[str, object]:
    """Generate a deterministic work order file for a worker.

    Pulls task spec and requirement README to populate the order file.
    The order file is the contract — the worker prompt is just a pointer.

    Pseudo-logic:
    1. Validate agent is lead-class (only leads generate orders)
    2. Fetch task record — need title, task_file, requirement_path
    3. Read task spec content for context
    4. Read requirement README if available for additional context
    5. Build structured order file with: Files, Fix Description, Test Command, Commit Message
    6. Write to .work/orders/worker-<worker>-task-<id>.md
    7. Return order file path for use in worker prompt
    """
    # --- Validate lead class ---
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("SELECT agent_class FROM agents WHERE name = ?", (agent_name,))
        row = cursor.fetchone()
        if not row:
            return {"error": f"BLOCKED: Agent '{agent_name}' not registered."}
        if row["agent_class"] != "lead":
            return {"error": f"BLOCKED: Only lead-class agents can generate work orders. '{agent_name}' is '{row['agent_class']}'."}

        # --- Fetch task record ---
        cursor.execute(
            "SELECT id, title, task_file, requirement_path, status, assigned_to FROM tasks WHERE id = ?",
            (task_id,),
        )
        task_row = cursor.fetchone()
        if not task_row:
            return {"error": f"Task #{task_id} not found."}

        task = dict(task_row)
    finally:
        conn.close()

    # --- Read task spec for context ---
    task_spec_content = ""
    task_file = task.get("task_file", "")
    if task_file and os.path.isfile(task_file):
        try:
            with open(task_file) as fh:
                task_spec_content = fh.read().strip()
        except OSError:
            pass  # Non-fatal — spec is supplementary context

    # --- Read requirement README for context ---
    req_content = ""
    req_path = task.get("requirement_path", "")
    if req_path:
        work_dir = get_runtime_dir()
        req_readme = os.path.join(work_dir, "requirements", req_path, "README.md")
        if os.path.isfile(req_readme):
            try:
                with open(req_readme) as fh:
                    req_content = fh.read().strip()
            except OSError:
                pass  # Non-fatal

    # --- Build the order file content ---
    # Use explicit arguments if provided; fall back to task spec
    effective_fix = fix_description.strip() if fix_description.strip() else task_spec_content
    effective_files = files_to_modify.strip() if files_to_modify.strip() else ""
    effective_test = test_command.strip() if test_command.strip() else "uv run pytest"
    effective_commit = commit_message.strip() if commit_message.strip() else f"fix: {task['title']}"

    lines: list[str] = []
    lines.append(f"# Work Order — Task #{task_id}")
    lines.append(f"**Title:** {task['title']}")
    lines.append(f"**Worker:** {worker_name}")
    lines.append(f"**Generated by:** {agent_name}")
    lines.append("")

    lines.append("## Fix Description")
    lines.append("")
    lines.append(effective_fix)
    lines.append("")

    lines.append("## Files to Modify")
    lines.append("")
    if effective_files:
        for f in effective_files.split(","):
            f = f.strip()
            if f:
                lines.append(f"- `{f}`")
    else:
        lines.append("_Determine from fix description above._")
    lines.append("")

    lines.append("## Test Command")
    lines.append("")
    lines.append(f"```bash\n{effective_test}\n```")
    lines.append("")

    lines.append("## Commit Message Format")
    lines.append("")
    lines.append(f"```\n{effective_commit}\n```")
    lines.append("")

    if req_content:
        lines.append("## Requirement Context")
        lines.append("")
        lines.append(req_content)
        lines.append("")

    lines.append("---")
    lines.append("**INSTRUCTIONS:** Read this file. Do exactly what it says. Write CHECKLIST.md first. Do not improvise.")
    lines.append("")

    # --- Write order file ---
    work_dir = get_runtime_dir()
    orders_dir = os.path.join(work_dir, "orders")
    os.makedirs(orders_dir, exist_ok=True)

    order_filename = f"worker-{worker_name}-task-{task_id}.md"
    order_path = os.path.join(orders_dir, order_filename)

    with open(order_path, "w") as fh:
        fh.write("\n".join(lines))

    return {
        "status": "order_generated",
        "task_id": task_id,
        "worker": worker_name,
        "order_file": order_path,
        "worker_prompt": f"Read {order_path}. Do exactly what it says. Write CHECKLIST.md first. Do not improvise.",
    }
